# Generated by Django 4.2.7 on 2023-12-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='body',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='shop',
            name='subject',
            field=models.CharField(max_length=16),
        ),
    ]
